package damas.entity;
// Generated 28/02/2020 18:06:38 by Hibernate Tools 4.3.1



/**
 * Moviments generated by hbm2java
 */
public class Moviments  implements java.io.Serializable {


     private MovimentsId id;
     private Partida partida;
     private String tablerojuego;

    public Moviments() {
    }

    public Moviments(MovimentsId id, Partida partida, String tablerojuego) {
       this.id = id;
       this.partida = partida;
       this.tablerojuego = tablerojuego;
    }
   
    public MovimentsId getId() {
        return this.id;
    }
    
    public void setId(MovimentsId id) {
        this.id = id;
    }
    public Partida getPartida() {
        return this.partida;
    }
    
    public void setPartida(Partida partida) {
        this.partida = partida;
    }
    public String getTablerojuego() {
        return this.tablerojuego;
    }
    
    public void setTablerojuego(String tablerojuego) {
        this.tablerojuego = tablerojuego;
    }




}


