package damas.entity;
// Generated 28/02/2020 18:06:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private Integer numeroPartida;
     private Date data;
     private int numeroMoviments;
     private String quiHaGuanyat;
     private Set movimentses = new HashSet(0);

    public Partida() {
    }

	
    public Partida(Date data, int numeroMoviments, String quiHaGuanyat) {
        this.data = data;
        this.numeroMoviments = numeroMoviments;
        this.quiHaGuanyat = quiHaGuanyat;
    }
    public Partida(Date data, int numeroMoviments, String quiHaGuanyat, Set movimentses) {
       this.data = data;
       this.numeroMoviments = numeroMoviments;
       this.quiHaGuanyat = quiHaGuanyat;
       this.movimentses = movimentses;
    }
   
    public Integer getNumeroPartida() {
        return this.numeroPartida;
    }
    
    public void setNumeroPartida(Integer numeroPartida) {
        this.numeroPartida = numeroPartida;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getNumeroMoviments() {
        return this.numeroMoviments;
    }
    
    public void setNumeroMoviments(int numeroMoviments) {
        this.numeroMoviments = numeroMoviments;
    }
    public String getQuiHaGuanyat() {
        return this.quiHaGuanyat;
    }
    
    public void setQuiHaGuanyat(String quiHaGuanyat) {
        this.quiHaGuanyat = quiHaGuanyat;
    }
    public Set getMovimentses() {
        return this.movimentses;
    }
    
    public void setMovimentses(Set movimentses) {
        this.movimentses = movimentses;
    }

    public void setMovimentses() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }




}


